#!/bin/bash
# Doble clic en este archivo para publicar los cambios en todos lados.
# Abre Terminal solo, hace todo el proceso y te dice cómo salió.
cd "$(dirname "$0")"

clear
echo ""
echo "  ============================================================"
echo "   ACTUALIZAR PLATAFORMA REAL ESTATE"
echo "  ============================================================"
echo ""
echo "   Esto publica los cambios en:"
echo "     - la página web (Vercel)"
echo "     - las apps instaladas en teléfono (tuya y de los asesores)"
echo "     - el paquete descargable de escritorio"
echo ""
echo "   Tarda entre 2 y 6 minutos: compila, publica y luego COMPRUEBA"
echo "   que el sitio de verdad esté sirviendo la versión nueva."
echo "   No cierres esta ventana."
echo ""
read -r -p "   Presiona ENTER para empezar (o cierra la ventana para cancelar): "
echo ""

if bash scripts/deploy.sh "$1"; then
  echo ""
  echo "  ============================================================"
  echo "   TERMINÓ BIEN — verificado en el sitio en vivo"
  echo "  ============================================================"
  echo ""
  echo "   Ya no hay que esperar: arriba se confirmó que el sitio"
  echo "   está sirviendo la versión nueva."
  echo ""
  echo "   1. En tu teléfono: cierra la app POR COMPLETO"
  echo "      (deslizar hacia arriba, no solo minimizar) y ábrela"
  echo "      otra vez con internet."
  echo "   2. Ahora sí, avisa a los asesores que hagan lo mismo."
  echo ""
else
  echo ""
  echo "  ============================================================"
  echo "   NO SE COMPLETÓ"
  echo "  ============================================================"
  echo ""
  echo "   Lee el mensaje de arriba: dice si falló al compilar"
  echo "   (no se publicó nada, no rompiste nada) o si subió a"
  echo "   GitHub pero el sitio no se actualizó."
  echo ""
  echo "   En cualquiera de los dos casos: NO les avises todavía"
  echo "   a los asesores. Copia todo el texto y pásamelo."
  echo ""
fi

echo "   Puedes cerrar esta ventana."
echo ""
read -r -p "   Presiona ENTER para salir: "
