-- =============================================================================
-- Bootstrap canónico de la sincronización EasyBroker
-- =============================================================================
-- Estas piezas existían en la base histórica, pero no en migrations/. Sin este
-- archivo un `supabase db reset` limpio falla cuando la migración multi-tenant
-- intenta alterar sync_estado/ingesta_log e indexar columnas CRM inexistentes.
-- Todo es idempotente para no afectar una instancia histórica reconciliada.

begin;

create or replace function public.norm_tel(p_telefono text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select case
    when regexp_replace(coalesce(p_telefono, ''), '[^0-9]', '', 'g') = '' then null
    when length(regexp_replace(coalesce(p_telefono, ''), '[^0-9]', '', 'g')) >= 10
      then right(regexp_replace(p_telefono, '[^0-9]', '', 'g'), 10)
    else regexp_replace(p_telefono, '[^0-9]', '', 'g')
  end;
$$;

revoke execute on function public.norm_tel(text) from public, anon;
grant execute on function public.norm_tel(text) to authenticated, service_role;

alter table public.usuarios
  add column if not exists eb_agent_id bigint;

alter table public.propiedades
  add column if not exists eb_public_id text,
  add column if not exists eb_public_url text,
  add column if not exists eb_sincronizado_en timestamptz,
  add column if not exists imagenes jsonb not null default '[]'::jsonb,
  add column if not exists amenidades jsonb not null default '[]'::jsonb,
  add column if not exists m2_terreno numeric not null default 0,
  add column if not exists medios_banos integer not null default 0,
  add column if not exists estacionamientos integer not null default 0,
  add column if not exists niveles integer,
  add column if not exists mantenimiento numeric,
  add column if not exists video_url text,
  add column if not exists tour_virtual_url text,
  add column if not exists colonia text not null default '',
  add column if not exists calle text not null default '',
  add column if not exists codigo_postal text not null default '',
  add column if not exists latitud numeric,
  add column if not exists longitud numeric,
  add column if not exists comision_tipo text,
  add column if not exists comision_valor numeric,
  add column if not exists comision_compartida_pct numeric,
  add column if not exists exclusiva boolean not null default false,
  add column if not exists crm_origen text,
  add column if not exists crm_id_interno text;

alter table public.leads
  add column if not exists eb_contact_request_id bigint,
  add column if not exists telefono_norm text,
  add column if not exists eb_property_id text,
  add column if not exists requiere_revision boolean not null default false,
  add column if not exists motivo_revision text;

create table if not exists public.sync_estado (
  proceso text primary key,
  ultimo_corte timestamptz,
  ultima_corrida timestamptz,
  ultimo_resultado text,
  actualizado_en timestamptz not null default now()
);

create table if not exists public.ingesta_log (
  id bigint generated by default as identity primary key,
  proceso text not null,
  corrida_en timestamptz not null default now(),
  fuente text,
  eb_contact_request_id bigint,
  eb_property_id text,
  telefono_norm text,
  resultado text not null,
  detalle text
);

alter table public.sync_estado enable row level security;
alter table public.ingesta_log enable row level security;
revoke all on public.sync_estado, public.ingesta_log from anon;
grant all on public.sync_estado, public.ingesta_log to service_role;

commit;
